// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFddnwC9jiua7cG-l_Om4mTDRki-o8jQU',
    appId: '1:961629805239:web:57d0ebcd961b39695c4b32',
    messagingSenderId: '961629805239',
    projectId: 'clowing-32621',
    authDomain: 'clowing-32621.firebaseapp.com',
    storageBucket: 'clowing-32621.appspot.com',
    measurementId: 'G-NV2529LLWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNlyd-EwWEoqg17ZPF3Tz1bF7btabplWw',
    appId: '1:961629805239:android:9b3cac220d2c0dbe5c4b32',
    messagingSenderId: '961629805239',
    projectId: 'clowing-32621',
    storageBucket: 'clowing-32621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlwLDPkO7hvXixk91cafdh1euEd0l6aI',
    appId: '1:961629805239:ios:bca792dcc753627e5c4b32',
    messagingSenderId: '961629805239',
    projectId: 'clowing-32621',
    storageBucket: 'clowing-32621.appspot.com',
    iosBundleId: 'com.example.clowingVer3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlwLDPkO7hvXixk91cafdh1euEd0l6aI',
    appId: '1:961629805239:ios:bca792dcc753627e5c4b32',
    messagingSenderId: '961629805239',
    projectId: 'clowing-32621',
    storageBucket: 'clowing-32621.appspot.com',
    iosBundleId: 'com.example.clowingVer3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFddnwC9jiua7cG-l_Om4mTDRki-o8jQU',
    appId: '1:961629805239:web:97e3438bf105f0275c4b32',
    messagingSenderId: '961629805239',
    projectId: 'clowing-32621',
    authDomain: 'clowing-32621.firebaseapp.com',
    storageBucket: 'clowing-32621.appspot.com',
    measurementId: 'G-7581ZE0JNG',
  );

}